### ISSUE TITLE
Button nonfunctional: "Stop Generation"

### ISSUE THREAD

**Issue by Myridium** [godly-devotion/MochiDiffusion#115]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

16GB

### What happened?

The "Stop Generation" button does not appear to do anything.

**Comment by Myridium** [comment]
Yes. The button appears to do nothing. Generation does not stop until it has completed all requested images.

**Comment by Myridium** [comment]
The button now works. The issue is intermittent.

**Comment by Zabriskije** [comment]
I had noticed this too. The button randomly freezes on "Stop Generation" until I click on an image or elsewhere. The next time it happens I'll try to post a video here.

**Comment by Zabriskije** [comment]
https://user-images.githubusercontent.com/101254295/215359316-34e85d18-fca8-4171-a900-9ad01ae51d2c.mov

**Comment by Zabriskije** [comment]
I've also noticed two more things:
- If a different model is selected while generating an image, `Stop Generation` will stop functioning. This seems related to the post above.
- If you hit the `Generate` button with a model that is not cached, and then switch to a different model (cached in this case, didn't try not cached ones, but I think the result will be the same) and hit the `Generate` button again, both images will be produced ― with some difficulties. In this case, a popup saying "Wait until the model is loaded" could solve the problem.

The video was ~5min long, I had cut it from 00:30 to 04:10 since it was just loading at that time. I've also attached the error shown for a fraction of a second near the end of the video.

https://user-images.githubusercontent.com/101254295/217337399-29efb5b7-ea42-4079-b0aa-103ac86cc8e1.mp4

<img width="1440" alt="more" src="https://user-images.githubusercontent.com/101254295/217337456-3454a689-e449-4c50-9e82-4deb62b3461e.png">
