### ISSUE TITLE
Size of the images

### ISSUE THREAD

**Issue by i3oc9i** [godly-devotion/MochiDiffusion#148]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

I'm really impressed by the speed, but there is no way ton specify the size of the image, at least to have some ratio, such as
 1:1, 5:4, 4:3, 19:16, ...

### Why do you think this should be added?

IMHO, without this option, it can be fast, but not so much useful

**Comment by godly-devotion** [comment]
This is currently a limitation of the newer Core ML models that need to be fixed by Apple's library. Here are several tickets that are tracking this issue upstream: 
https://github.com/apple/ml-stable-diffusion/issues/64
https://github.com/apple/ml-stable-diffusion/issues/70
https://github.com/apple/ml-stable-diffusion/issues/69

However `original` Core ML models can be created with different sizes other than 512x512. Some of them have been created and made available [here](https://huggingface.co/coreml). If the filename includes a size, it will generate that size.
