### ISSUE TITLE
v3.2 crashes when trying to generate img2img

### ISSUE THREAD

**Issue by firingmalaysia** [godly-devotion/MochiDiffusion#248]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

8GB

### What happened?

This problem can be reproduced every time

Steps to reproduce problem:

- Generate any image with any prompt (I used Deliberate)
- Insert the image as a template into img2img
- Generate a new image
- Application crashes instantly

This crash did not occur under v3.1

**Comment by jrittvo** [comment]
2:07 PM
godly-devotion

It has been brought to my attention that due to a change in Apple's code, Mochi Diffusion v3.2 requires reconverting the VAEEncoder.mlmodelc using the updated conversion script to use the starting image feature (Image2Image). 

If this is not possible and you must use Image2Image, please use v3.1 for now.

**Comment by Exynos-8890** [comment]
I meet the same bug on my m1 macbook air too. Hope for solving.

**Comment by antigo333** [comment]
same here M1 Silicon

**Comment by godly-devotion** [comment]
As @jrittvo quoted, rather than a bug, this is the result of some changes that occurred in Apple's Stable Diffusion Core ML code.
