### ISSUE TITLE
Order - Newest First and click a picture will make it order with Oldest First

### ISSUE THREAD

**Issue by TimYao18** [godly-devotion/MochiDiffusion#289]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

16GB

### What happened?

When switch Oldest First to Newest First, the image order is sorted with Newest First. But when clicking on any image in the list, it will auto-sort again into Oldest First.

**Comment by jrittvo** [comment]
So far I am unable to duplicate this with my install of 4.1.3.  Just to confirm, when you say "any image in the list" you mean an image displayed in the image gallery?

**Comment by TimYao18** [comment]
I put the [screen record here](https://drive.google.com/file/d/1dSdyOgjGpV7SanwHBSVJXdzv0nfKJtAm/view?usp=sharing)
As the video shows, when I click the sort item "Newest First", it will sort the image list. But when I click on an image, it sorts back.

**Comment by jrittvo** [comment]
Tell me if it looks like I am doing something different from you.  I even ran a ControlNet just before, because it looks like you had done that.  I'm not doubting your screencap.  If we are both following the same steps, then 4.1.3 has another intermittent bug that we need to chase down.

https://github.com/godly-devotion/MochiDiffusion/assets/114269461/801c43db-36ea-4881-9ee8-c632b2ef592b

**Comment by TimYao18** [comment]
Looks like we do nothing different. I also tried removing this app and re-download the 4.1.3 version, but it still happens at the first startup. It's a minor issue, just let you know.

**Comment by jrittvo** [comment]
We are learning that minor issues can be the first sign of more serious issues, so it is a very valid bug report!

I am running the current macOS 13.5 beta, which I think is now an RC.  It is a long-shot, but if someone reads this thread who is on 13.4.x, please take a moment and see what happens when you follow the steps in the top post.  I can't think of any other variable besides that.

**Comment by Pindar777** [comment]
I can replace the bug with 4.1.3 on macOS 14.0 Beta and would like to add that after clicking on an image the ordering switches back to "Oldest first" without updating the variable in the GUI.

**Comment by jrittvo** [comment]
@TimYao18 , what version of macOS are you running?

**Comment by TimYao18** [comment]
macOS 14.0 Beta (23A5301g)

**Comment by jrittvo** [comment]
Thanks.  So that is 2 with the issue on 14 and 1 without it on 13.  Clues.  I will try Mochi 4.1.3 in my 14 beta install tonight.  I also plan to try building the current Mochi source in the next day with Xcode 15 beta for macOS 14.  I'll post here if I find out anything useful.  Best would be if the Xcode build throws an erorr that relates to this bug, so we'd know what to look at for a fix.

**Comment by jrittvo** [comment]
Now it's 3 with the issue on macOS 14.  I gotta say, as far a bugs go, this one is kind of humorous.  Tomorrow I'll try the Mochi build for macOS 14, and we'll take it from there.  I guess it is time run in the 14 beta as much as in 13.

**Comment by jrittvo** [comment]
I have no idea what this really means (yet), but this warning, one of several that are thrown when the current Mochi code is built with Xcode 15beta4 for macOS 14, is maybe related to this issue.
```
Gallery View.swift
  'onChange(of:perform:)' was deprecated in macOS 14.0: Use 'onChange with a two or zero parameter action closure instead.
```

**Comment by TimYao18** [comment]
I think it's not fixed. I tried the v4.2, and the order/sort is still strange.
The image sort will become Newest first when you first time switch to Newest First, it looks good.
And then you click one image, ex: the first image (Newest one), the order will become Oldest first and focus on the last one (Newest image).
