### ISSUE TITLE
While reusing old prompts and settings, new models gets stuck at "Loading Model..." message.

### ISSUE THREAD

**Issue by krv5vignesh** [godly-devotion/MochiDiffusion#304]
### Processor

M1 (or later)

### Memory

16GB

### What happened?

Mac OS - 14.0
Mochi Diffusion - 4.2

I updated to 4.2 and then tried to load a new model. I was reusing old prompts and other settings from a previously generated image with only the model changing. Since the model loads for the first time I got the "Loading Model..." message but it got stuck like that for more than 20 minutes when I finally killed the app. I tried again after changing my settings and prompt and clicked generate. This time the model loaded after some time and generated the message. I tried this with three separate new models (both SDXL and 1.5) and got the same issue.

**Comment by jrittvo** [comment]
There are situations where the ANECompilerService process gets stuck, and restarting the Mochi app is not sufficient to the shut it down.  When this happens, a full system reboot is the easiest way to to get back on track.  It sounds like this ANECompilerService issue is your problem.  What happens if you try these models/settings after you reboot your computer?

**Comment by krv5vignesh** [comment]
Looks like the ANECompilerService might be the issue. I can see it having high memory usage in the activity monitor. I rebooted like you suggested and it works after reboot with the same settings.

**Comment by godly-devotion** [comment]
Unfortunately this is something that Apple needs to improve upon and is out of our hands. As mentioned, if the initial loading takes more than 5 min you can either reboot or force quit ANECompilerService using Activity Monitor.
